const COLOR_BORDER = "#D9E1EC";
const COLOR_NUTRAL = "#858585";
const COLOR_ACTIVE = "#06A561";
const COLOR_DEACTIVATED = "#F0142F";

const LBL_UNSET = "...";
const LBL_YES = "Yes";
const LBL_NO = "No";

export {COLOR_BORDER, COLOR_NUTRAL, COLOR_ACTIVE, COLOR_DEACTIVATED, LBL_UNSET, LBL_YES, LBL_NO};